name: 'Branch Naming Check'
on: pull_request

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: 'DMVP-[0-9]*' # Regex the branch should match. This example enforces grouping
          allowed_prefixes: 'DMVP-' # All branches should start with the given prefix
          ignore: master,develop # Ignore exactly matching branch names from convention
          min_length: 5 # Min length of the branch name
          max_length: 30 # Max length of the branch name
