name: Checkov
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        path:
          - ./
          - modules/alerts
          - modules/security-hub
          - modules/billing
          - modules/cloudwatch-alarm-actions
          - modules/dashboard
          - modules/eventbridge
          - modules/sns_to_lambda
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@a8664e3a0549367977f0cda990a34311835c87c0 # v12
        with:
          directory: ${{ matrix.path }}
          framework: terraform
          download_external_modules: true
          output_format: cli
          soft_fail: true
