name: Terraform Test
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  terraform-validate:
    permissions:
      actions: write
      contents: write
      discussions: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - /
     
    steps:
    - uses: dasmeta/reusable-actions-workflows/terraform-test@4.2.0
      with:
        aws-region: ${{ secrets.AWS_REGION}}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        path: ${{ matrix.path }}
      continue-on-error: true
