name: Tflint
on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  terraform-validate:
    permissions:
      actions: write
      contents: write
      discussions: write
      pull-requests: write
      id-token: write
      security-events: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - modules/alerts
          - modules/security-hub
          - modules/billing
          - modules/cloudwatch-alarm-actions
          - modules/dashboard
          - modules/eventbridge
          - modules/sns_to_lambda
    steps:
      - uses: actions/checkout@v7
      - uses: terraform-linters/setup-tflint@v6
      - name: Run TFLint
        run: >-
          tflint
          --chdir="${{ matrix.path }}"
          --enable-rule=terraform_unused_declarations
          --minimum-failure-severity=error
          --format=compact
